random_state: 5
#random_state: 7
#random_state: 11

#num_symbols: 3
num_symbols: 101
#num_symbols: 1013
#num_symbols: 10059
#num_symbols: 20147
#num_symbols: 25028
#num_symbols: 26007
#num_symbols: 27137
#num_symbols: 28197
#num_symbols: 29041
#num_symbols: 30591

#sequence_length: 750
sequence_length: 1000
#sequence_length: 1500
#sequence_length: 2000

#batch_size: 32
#batch_size: 64
#batch_size: 128
#batch_size: 256
#batch_size: 512
#batch_size: 1024
batch_size: 2048
#batch_size: 4096
#batch_size: 8192

#learning_rate: 0.01
learning_rate: 0.001

num_epochs: 1
#num_epochs: 3
#num_epochs: 10
#num_epochs: 100
#num_epochs: 1000
